
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 29 17:02:06 MDT 2017
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PALABRA_RESERVADA_COM = 27;
  public static final int PALABRA_RESERVADA_SI = 47;
  public static final int PALABRA_RESERVADA_ENT = 32;
  public static final int PALABRA_RESERVADA_DET = 28;
  public static final int PALABRA_RESERVADA_BOO = 46;
  public static final int PALABRA_RESERVADA_S = 41;
  public static final int PALABRA_RESERVADA_MOVAD = 39;
  public static final int OP_RELACIONAL_MAQUE = 12;
  public static final int PALABRA_RESERVADA_DETENTE = 29;
  public static final int OP_ARITMETICO_SUB = 3;
  public static final int SIMBOLO_AGRUPACION_PACIERRA = 16;
  public static final int SIMBOLO_AGRUPACION_PCOMA = 18;
  public static final int IDENTIFICADOR = 45;
  public static final int SIMBOLO_AGRUPACION_PABRE = 15;
  public static final int PALABRA_RESERVADA_ACTM = 23;
  public static final int PALABRA_RESERVADA_FUNC = 35;
  public static final int CADENA_DESCONOCIDA = 49;
  public static final int PALABRA_RESERVADA_VDD = 44;
  public static final int EOF = 0;
  public static final int SIMBOLO_AGRUPACION_CCIERRA = 20;
  public static final int OP_RELACIONAL_MAIGUAL = 9;
  public static final int error = 1;
  public static final int COMA = 21;
  public static final int NUM_FLOTANTE = 6;
  public static final int PALABRA_RESERVADA_CJT = 25;
  public static final int PALABRA_RESERVADA_FLS = 34;
  public static final int OP_RELACIONAL_MEIGUAL = 10;
  public static final int PALABRA_RESERVADA_FLO = 33;
  public static final int PALABRA_RESERVADA_EFEC = 31;
  public static final int OP_RELACIONAL_IIGUAL = 8;
  public static final int SIMBOLO_AGRUPACION_DOSP = 17;
  public static final int OP_ARITMETICO_DIV = 5;
  public static final int FIN_LINEA = 22;
  public static final int PALABRA_RESERVADA_GIRAI = 36;
  public static final int OP_RELACIONAL_DIFERENTE = 11;
  public static final int SIMBOLO_DESCONOCIDO = 50;
  public static final int PALABRA_RESERVADA_GIRAD = 37;
  public static final int PALABRA_RESERVADA_ECD = 30;
  public static final int OP_ARITMETICO_MUL = 4;
  public static final int OP_ARITMETICO_ADD = 2;
  public static final int OP_RELACIONAL_MEQUE = 13;
  public static final int NUM_ENTERO = 7;
  public static final int SIMBOLO_AGRUPACION_CABRE = 19;
  public static final int SIMBOLO_ASIGNACION = 14;
  public static final int PALABRA_RESERVADA_LUZ = 38;
  public static final int PALABRA_RESERVADA_CLX = 26;
  public static final int PALABRA_RESERVADA_SPD = 43;
  public static final int PALABRA_RESERVADA_SINO = 48;
  public static final int PALABRA_RESERVADA_SN = 42;
  public static final int PALABRA_RESERVADA_MOVAT = 40;
  public static final int PALABRA_RESERVADA_APG = 24;
}

